### ISSUE TITLE
# Flutter: Bottom overflowed by infinity pixels

### ISSUE THREAD

**Issue by wileecoyote2point0** [wileecoyote2point0/math_game#1]
I have written this code for a login page and a signup page for a new messenger game.

In the emulator I get the error message: "Bottom Overflowed By Infinity Pixels"

Can anyone guide me in the right direction?

I tried to implement scrolling view and I tried MainAxisSize.Min 
but can't seem to get it to work.

**Comment by fabiopiccioni** [comment]
Hi, did you solved? How?
